# Generated by Django 5.2.8 on 2025-11-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAW', '출금')], max_length=10, verbose_name='거래 유형')),
                ('amount', models.IntegerField(verbose_name='거래 금액')),
                ('category', models.CharField(choices=[('food', '식비'), ('transport', '교통'), ('shopping', '쇼핑'), ('income', '수입'), ('etc', '기타')], max_length=20, verbose_name='카테고리')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='메모')),
                ('transacted_at', models.DateTimeField(verbose_name='거래 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account', verbose_name='계좌')),
            ],
            options={
                'ordering': ['-transacted_at'],
            },
        ),
    ]
