# Generated by Django 5.2.8 on 2025-11-24 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', '입금'), ('EXPENSE', '출금')], max_length=10)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('category', models.CharField(choices=[('food', '식비'), ('transport', '교통'), ('shopping', '쇼핑'), ('income', '수입'), ('etc', '기타')], max_length=20)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('transaction_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_at'],
            },
        ),
    ]
