# Generated by Django 5.2.8 on 2025-11-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_at', '-id']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=100, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_at',
            field=models.DateField(verbose_name='거래일'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출')], default='EXPENSE', max_length=10, verbose_name='구분'),
        ),
    ]
