# Generated by Django 5.2.8 on 2025-11-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_at']},
        ),
    ]
