# Generated by Django 5.2.8 on 2025-11-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', '입금'), ('withdraw', '출금')], default='withdraw', max_length=10, verbose_name='거래 유형'),
        ),
    ]
