# Generated by Django 5.2.8 on 2025-11-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('식비', '식비'), ('카페/간식', '카페/간식'), ('교통/차량', '교통/차량'), ('쇼핑/패션', '쇼핑/패션'), ('마트/편의점', '마트/편의점'), ('주거/통신', '주거/통신'), ('의료/건강', '의료/건강'), ('문화/여가', '문화/여가'), ('여행/숙박', '여행/숙박'), ('교육/학습', '교육/학습'), ('경조사/선물', '경조사/선물'), ('급여', '급여'), ('용돈', '용돈'), ('금융이자', '금융이자'), ('기타', '기타')], default='식비', max_length=50, verbose_name='카테고리'),
        ),
    ]
