# Generated by Django 5.2.8 on 2025-11-25 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(choices=[('TOTAL_SPENDING', '총 지출'), ('TOTAL_INCOME', '총 수입')], max_length=30, verbose_name='분석 대상')),
                ('type', models.CharField(choices=[('DAILY', '일별'), ('WEEKLY', '주별'), ('MONTHLY', '월별'), ('YEARLY', '연도별')], max_length=20, verbose_name='분석 단위')),
                ('period_start', models.DateField(verbose_name='분석 시작일')),
                ('period_end', models.DateField(verbose_name='분석 종료일')),
                ('description', models.TextField(blank=True, verbose_name='분석 설명')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='analysis/', verbose_name='결과 그래프')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
