# Generated by Django 5.2.8 on 2025-11-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='difference',
            field=models.IntegerField(default=0, verbose_name='차액'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_income',
            field=models.IntegerField(default=0, verbose_name='총 수입'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_spending',
            field=models.IntegerField(default=0, verbose_name='총 지출'),
        ),
    ]
